name: Send Slack Message
description: "Send slack message to a channel"
    
inputs:
  slack-webhook-url:
    description: 'Slack webhook url'
    required: true
  job-status:
    description: 'Job status'
    required: true
  pull_request_url:
    description: 'Pull request url'
    required: true
  head_commit_url:
    description: 'Head commit url'
    required: true

runs:
  using: "composite"
  steps:
    - name: send slack message
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook: ${{ inputs.slack-webhook-url }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "GitHub Action build result: ${{ inputs.job-status }}\n${{ inputs.pull_request_url || inputs.head_commit_url }}"
          }
