name: 'Docker Build and Push'
description: 'Build and push Docker images'

inputs:
  dockerfile-tag:
    description: 'Tag to replace in Dockerfile'
    required: true
  docker-tags:
    description: 'Newline-separated list of Docker tags'
    required: true
  dockerhub-username:
    description: 'DockerHub username'
    required: true
  dockerhub-token:
    description: 'DockerHub token'
    required: true
  buildcloud-endpoint:
    description: 'Buildcloud endpoint'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Set up Docker Buildx with cloud driver
      uses: docker/setup-buildx-action@v3
      with:
        version: "lab:latest"
        driver: cloud
        endpoint: ${{ inputs.buildcloud-endpoint }}

    - name: Update Dockerfile
      shell: bash
      run: sed -i "s/@ngiab_dev/@ngiab_$(echo ${{ inputs.dockerfile-tag }} | sed 's/\./\\./g')/g" ./docker/Dockerfile

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./docker
        file: ./docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ inputs.docker-tags }}